DROP DATABASE IF EXISTS lab04;
CREATE DATABASE lab04;
USE lab04;

CREATE TABLE NHANVIEN (
	HOTEN VARCHAR(50),
    MASONV INT PRIMARY KEY,
    NGSINH DATE,
    DIACHI VARCHAR(50),
    GIOITINH ENUM ("NAM", "NU") UNIQUE NOT NULL,
    LUONG DOUBLE,
    MASONGS INT,
    MASODV INT
    );
    
CREATE TABLE DONVI (
	TENDV VARCHAR(50),
    MASODV INT PRIMARY KEY,
    NGAYBATDAU DATE
    );
    
CREATE TABLE DONVI_DIADIEM (
	MASODV INT,
    DIADIEMDV VARCHAR(50),
    PRIMARY KEY (MASPDV,DIADIEMDV)
    );
    
CREATE TABLE DUAN (
	TENDA VARCHAR(50),
    MASODA INT PRIMARY KEY,
    DIADIEMDA VARCHAR(50),
    MASODV INT
    );
    
CREATE TABLE THAMGIA (
	MASONV INT,
    MASODA INT,
    SOGIO TIME,
    PRIMARY KEY (MASONV,MASODA)
    );
    
CREATE TABLE PHUTHUOC (
	MASONV INT,
    TENCON VARCHAR(50),
    GIOITINH ENUM ("NAM", "NU") UNIQUE NOT NULL,
    NGSINH DATE,
    PRIMARY KEY (MASONV,TENCON)
    );