DROP DATABASE IF EXISTS projectmanagement;
CREATE DATABASE projectmanagement;
USE projectmanagement;

CREATE TABLE NHANVIEN (
	HONV VARCHAR(15),
    TENLOT VARCHAR(15),
    TENNV VARCHAR(15),
    MANV VARCHAR(9) PRIMARY KEY,
    NGSINH DATE,
    DCHI VARCHAR(30),
    PHAI ENUM("NAM","NU") UNIQUE NOT NULL,
    LUONG DOUBLE,
    MA_NQL VARCHAR(30),
    PHG INT
    );
    
CREATE TABLE PHONGBAN (
	TENPHG VARCHAR(15),
    MAPHG INT PRIMARY KEY,
    TRPHG VARCHAR(9),
    NG_NHANCHUC DATE,
    FOREIGN KEY (TRPHG) REFERENCES NHANVIEN (MANV)
);

CREATE TABLE DIADIEM_PHG (
	MAPHG INT ,
    DIADIEM VARCHAR(15),
    PRIMARY KEY (MAPHG, DIADIEM),
    FOREIGN KEY (MAPHG) REFERENCES PHONGBAN (MAPHG)
);

CREATE TABLE DEAN (
	TENDA VARCHAR(15),
    MADA INT PRIMARY KEY,
    DDIEM_DA VARCHAR(15),
    PHONG INT,
    FOREIGN KEY (PHONG) REFERENCES PHONGBAN (MAPHG)
);

CREATE TABLE CONGVIEC (
	MADA INT ,
    STT INT,
    TEN_CONG_VIEC VARCHAR(50),
    PRIMARY KEY (MADA, STT),
    FOREIGN KEY (MADA) REFERENCES DEAN (MADA)
);

CREATE TABLE PHANCONG (
	MA_NVIEN VARCHAR(9) PRIMARY KEY,
    MADA INT,
    STT INT,
    THOIGIAN DOUBLE,
    FOREIGN KEY (MA_NVIEN) REFERENCES NHANVIEN (MANV),
    FOREIGN KEY (MADA,STT) REFERENCES CONGVIEC (MADA,STT)
);

CREATE TABLE THANNHAN (
	MA_NVIEN VARCHAR(9) PRIMARY KEY,
    TENTN VARCHAR(15),
    PHAI ENUM("NAM","NU") UNIQUE NOT NULL,
    NGSINH DATE,
    QUANHE VARCHAR(15),
    FOREIGN KEY (MA_NVIEN) REFERENCES NHANVIEN (MANV)
);